# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# XDC: new/hdmi.xdc

# Block Designs: bd/hdmi_out/hdmi_out.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_out || ORIG_REF_NAME==hdmi_out} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_rgb2dvi_0_0/hdmi_out_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_out_rgb2dvi_0_0 || ORIG_REF_NAME==hdmi_out_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_clk_wiz_0_0/hdmi_out_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_out_clk_wiz_0_0 || ORIG_REF_NAME==hdmi_out_clk_wiz_0_0} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_xlconstant_0_1/hdmi_out_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_out_xlconstant_0_1 || ORIG_REF_NAME==hdmi_out_xlconstant_0_1} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_xlconstant_0_2/hdmi_out_xlconstant_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_out_xlconstant_0_2 || ORIG_REF_NAME==hdmi_out_xlconstant_0_2} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_v_tc_0_0/hdmi_out_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_out_v_tc_0_0 || ORIG_REF_NAME==hdmi_out_v_tc_0_0} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_hdmi_code_0_0/hdmi_out_hdmi_code_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_out_hdmi_code_0_0 || ORIG_REF_NAME==hdmi_out_hdmi_code_0_0} -quiet] -quiet

# IP: bd/hdmi_out/ip/hdmi_out_constant_0_0/hdmi_out_constant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_out_constant_0_0 || ORIG_REF_NAME==hdmi_out_constant_0_0} -quiet] -quiet

# XDC: c:/Users/Home/Documents/FPGASummerProject/Project/matrix_multiplier/matrix_multiplier.gen/sources_1/bd/hdmi_out/hdmi_out_ooc.xdc
